language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - python setup.py install
    - pip install pylint pytest coverage
script:
    - coverage run --source linode_api -m pytest
    - coverage report
    - pylint linode
